//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shipping
    {
        public int Id { get; set; }
        [Required()]
        [StringLength(20, MinimumLength =2, ErrorMessage ="Please enter a valid city")]
        public string City { get; set; }
        [Required()]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Please enter a valid country")]
        public string Country { get; set; }
        [Required()]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Please enter a valid street")]
        public string Street { get; set; }
        [Required()]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "Phone number must be 8 digits")]
        public string Phone { get; set; }
        [Required()]
        [StringLength(5, MinimumLength = 5, ErrorMessage = "Zip number must be 8 digits")]
        public string Zip { get; set; }
        public string CustomerName { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
